In [38]:
import numpy as np

X=np.array([[4,1,4],[4,2,3]])
print (X.shape)
A=np.array([2,2,2])
#A = vstack((A, X[X[:,0] < 3]))

X=np.vstack((X,A))

c=np.where(X<4)
a=np.array(np.where(X<4))
d=np.vstack((c[1],c[0]))
#d=np.divide(X,c)
#print (d[0,0])
print(d)
print (a)
a[[0,1]]=a[[1,0]]
print(a)

(2, 3)
[[1 1 2 0 1 2]
 [0 1 1 2 2 2]]
[[0 1 1 2 2 2]
 [1 1 2 0 1 2]]
[[1 1 2 0 1 2]
 [0 1 1 2 2 2]]
